package DAL;
// Generated 28-dec-2014 18:58:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {

    public static final int MINLENGTH = 5;
    public static final int MAXLENGTH = 25;
    private static String error;
    
    private Integer id;
    private String name;
    private String password;
    private boolean admin;
    private Set characters = new HashSet(0);

    public Account() {
    }

	
    public Account(String name, String password, boolean admin) {
        this.name = name;
        this.password = password;
        this.admin = admin;
    }
    public Account(String name, String password, boolean admin, Set characters) {
       this.name = name;
       this.password = password;
       this.admin = admin;
       this.characters = characters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Set characters) {
        this.characters = characters;
    }

    public boolean IsValid(){
        
        if (!name.matches("^[a-zA-Z]*$")) {
            error = "Name can only contain letters.";
            return false;
        }
        
        if(name.length() < MINLENGTH){
            error = "Name has to be at least "+ MINLENGTH +" letters.";
            return false;
        }
        
        if(name.length() > MAXLENGTH){
            error = "Name must be less than "+ MAXLENGTH +" letters.";
            return false;
        }
        
        
        
        return true;
    }

    public String getError() {
        return error;
    }

}


