package DAL;
// Generated 28-dec-2014 18:58:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private boolean admin;
     private Set characters = new HashSet(0);

    public Account() {
    }

	
    public Account(String name, String password, boolean admin) {
        this.name = name;
        this.password = password;
        this.admin = admin;
    }
    public Account(String name, String password, boolean admin, Set characters) {
       this.name = name;
       this.password = password;
       this.admin = admin;
       this.characters = characters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Set characters) {
        this.characters = characters;
    }




}


