package DAL;
// Generated 28-dec-2014 18:58:35 by Hibernate Tools 4.3.1



/**
 * Character generated by hbm2java
 */
public class Character  implements java.io.Serializable {
    public static final int MINLENGTH = 3;
    public static final int MAXLENGTH = 25;
    private static String error;

    private Integer id;
    private Account account;
    private Charclass charclass;
    private Item itemByBootsItemId;
    private Item itemByWeaponItemId;
    private Item itemByLegsItemId;
    private Item itemByChestItemId;
    private Race race;
    private String name;

    public Character() {
    }

	
    public Character(Account account, Charclass charclass, Race race, String name) {
        this.account = account;
        this.charclass = charclass;
        this.race = race;
        this.name = name;
    }
    public Character(Account account, Charclass charclass, Item itemByBootsItemId, Item itemByWeaponItemId, Item itemByLegsItemId, Item itemByChestItemId, Race race, String name) {
       this.account = account;
       this.charclass = charclass;
       this.itemByBootsItemId = itemByBootsItemId;
       this.itemByWeaponItemId = itemByWeaponItemId;
       this.itemByLegsItemId = itemByLegsItemId;
       this.itemByChestItemId = itemByChestItemId;
       this.race = race;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Charclass getCharclass() {
        return this.charclass;
    }
    
    public void setCharclass(Charclass charclass) {
        this.charclass = charclass;
    }
    public Item getItemByBootsItemId() {
        return this.itemByBootsItemId;
    }
    
    public void setItemByBootsItemId(Item itemByBootsItemId) {
        this.itemByBootsItemId = itemByBootsItemId;
    }
    public Item getItemByWeaponItemId() {
        return this.itemByWeaponItemId;
    }
    
    public void setItemByWeaponItemId(Item itemByWeaponItemId) {
        this.itemByWeaponItemId = itemByWeaponItemId;
    }
    public Item getItemByLegsItemId() {
        return this.itemByLegsItemId;
    }
    
    public void setItemByLegsItemId(Item itemByLegsItemId) {
        this.itemByLegsItemId = itemByLegsItemId;
    }
    public Item getItemByChestItemId() {
        return this.itemByChestItemId;
    }
    
    public void setItemByChestItemId(Item itemByChestItemId) {
        this.itemByChestItemId = itemByChestItemId;
    }
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public boolean IsValid(){
        
        if (!name.matches("^[a-zA-Z ]*$")) {
            error = "Name can only contain letters and spaces.";
            return false;
        }
        
        if (!name.matches("^[[\\p{Alpha}]]+( [[\\p{Alpha}}]]+)*$")) {
            error = "Name has invalid use of spaces.";
            return false;
        }
        
        if(name.length() < MINLENGTH){
            error = "Name has to be at least "+ MINLENGTH +" letters.";
            return false;
        }
        
        if(name.length() > MAXLENGTH){
            error = "Name must be less than "+ MAXLENGTH +" letters.";
            return false;
        }
        
        return true;
    }

    public String getError() {
        return error;
    }

    @Override
    public String toString() {
        return name;
    }
    
}


