package DAL;
// Generated 28-dec-2014 18:58:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Charclass generated by hbm2java
 */
public class Charclass  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String iconPath;
     private Set characters = new HashSet(0);

    public Charclass() {
    }

	
    public Charclass(String name, String iconPath) {
        this.name = name;
        this.iconPath = iconPath;
    }
    public Charclass(String name, String iconPath, Set characters) {
       this.name = name;
       this.iconPath = iconPath;
       this.characters = characters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIconPath() {
        return this.iconPath;
    }
    
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }
    public Set getCharacters() {
        return this.characters;
    }
    
    public void setCharacters(Set characters) {
        this.characters = characters;
    }




}


