package DAL;
// Generated 28-dec-2014 18:58:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Slot generated by hbm2java
 */
public class Slot  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set items = new HashSet(0);

    public Slot() {
    }

	
    public Slot(String name) {
        this.name = name;
    }
    public Slot(String name, Set items) {
       this.name = name;
       this.items = items;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

    @Override
    public String toString() {
        return name;
    }
    
    
}


