package DAL;
// Generated 4-jan-2015 22:28:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set items = new HashSet(0);

    public Attribute() {
    }

	
    public Attribute(String name) {
        this.name = name;
    }
    public Attribute(String name, Set items) {
       this.name = name;
       this.items = items;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


