package DAL;
// Generated 4-jan-2015 22:28:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer id;
     private Attribute attribute;
     private Slot slot;
     private String name;
     private int attribute1value;
     private String iconPath;
     private Set charactersForBootsItemId = new HashSet(0);
     private Set charactersForWeaponItemId = new HashSet(0);
     private Set charactersForLegsItemId = new HashSet(0);
     private Set charactersForChestItemId = new HashSet(0);

    public Item() {
    }

	
    public Item(Attribute attribute, Slot slot, String name, int attribute1value, String iconPath) {
        this.attribute = attribute;
        this.slot = slot;
        this.name = name;
        this.attribute1value = attribute1value;
        this.iconPath = iconPath;
    }
    public Item(Attribute attribute, Slot slot, String name, int attribute1value, String iconPath, Set charactersForBootsItemId, Set charactersForWeaponItemId, Set charactersForLegsItemId, Set charactersForChestItemId) {
       this.attribute = attribute;
       this.slot = slot;
       this.name = name;
       this.attribute1value = attribute1value;
       this.iconPath = iconPath;
       this.charactersForBootsItemId = charactersForBootsItemId;
       this.charactersForWeaponItemId = charactersForWeaponItemId;
       this.charactersForLegsItemId = charactersForLegsItemId;
       this.charactersForChestItemId = charactersForChestItemId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Attribute getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    public Slot getSlot() {
        return this.slot;
    }
    
    public void setSlot(Slot slot) {
        this.slot = slot;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getAttribute1value() {
        return this.attribute1value;
    }
    
    public void setAttribute1value(int attribute1value) {
        this.attribute1value = attribute1value;
    }
    public String getIconPath() {
        return this.iconPath;
    }
    
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }
    public Set getCharactersForBootsItemId() {
        return this.charactersForBootsItemId;
    }
    
    public void setCharactersForBootsItemId(Set charactersForBootsItemId) {
        this.charactersForBootsItemId = charactersForBootsItemId;
    }
    public Set getCharactersForWeaponItemId() {
        return this.charactersForWeaponItemId;
    }
    
    public void setCharactersForWeaponItemId(Set charactersForWeaponItemId) {
        this.charactersForWeaponItemId = charactersForWeaponItemId;
    }
    public Set getCharactersForLegsItemId() {
        return this.charactersForLegsItemId;
    }
    
    public void setCharactersForLegsItemId(Set charactersForLegsItemId) {
        this.charactersForLegsItemId = charactersForLegsItemId;
    }
    public Set getCharactersForChestItemId() {
        return this.charactersForChestItemId;
    }
    
    public void setCharactersForChestItemId(Set charactersForChestItemId) {
        this.charactersForChestItemId = charactersForChestItemId;
    }




}


