/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.Item;
import DAL.Slot;
import Services.UIException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author LanceDH
 */
public class AdminWindow extends javax.swing.JFrame {

    private DAL.Account _selectedAccount;
    private DAL.Item _selectedItem;
    private DAL.Character _selectedCharacter;
    
    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
        
        InitAccount();
        InitItem();
        InitCharacter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnl_MainPanel = new javax.swing.JTabbedPane();
        pnl_Accounts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Accounts_AccountList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txt_Accounts_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Accounts_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Accounts_Password = new javax.swing.JTextField();
        cbx_Accounts_Admin = new javax.swing.JCheckBox();
        btn_Accounts_Save = new javax.swing.JButton();
        btn_Accounts_Delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_Accounts_Characters = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        btn_Accounts_ViewCharacter = new javax.swing.JButton();
        btn_Accounts_DeleteCharacter = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_Accounts_Id = new javax.swing.JTextField();
        pnl_Characters = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_Characters_CharacterList = new javax.swing.JList();
        txt_Characters_Search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Character_AccountId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_Characters_Id = new javax.swing.JTextField();
        lbl_Characters_Name = new javax.swing.JLabel();
        txt_Characters_Name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmb_Characters_Race = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cmb_Characters_Class = new javax.swing.JComboBox();
        tpnl_Gear = new javax.swing.JTabbedPane();
        weapon = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_Characters_weaponId = new javax.swing.JTextField();
        lbl_WeaponName = new javax.swing.JLabel();
        lbl_WeaponAttribute1 = new javax.swing.JLabel();
        lbl_WeaponAttribute2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_Characters_ChestId = new javax.swing.JTextField();
        lbl_ChestName = new javax.swing.JLabel();
        lbl_ChestAttribute1 = new javax.swing.JLabel();
        lbl_ChestAttribute2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_Characters_LegsId = new javax.swing.JTextField();
        lbl_LegsName = new javax.swing.JLabel();
        lbl_LegsAttribute1 = new javax.swing.JLabel();
        lbl_LegsAttribute2 = new javax.swing.JLabel();
        Boots = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txt_Characters_BootsId = new javax.swing.JTextField();
        lbl_BootsName = new javax.swing.JLabel();
        lbl_BootsAttribute1 = new javax.swing.JLabel();
        lbl_BootsAttribute2 = new javax.swing.JLabel();
        btn_Characters_Save = new javax.swing.JButton();
        btn_Characters_Delete = new javax.swing.JButton();
        pnl_Items = new javax.swing.JPanel();
        cmb_Items_SlotList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Items_ItemList = new javax.swing.JList();
        txt_Items_Search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Items_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_Items_Slot = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmb_Items_Attribute1 = new javax.swing.JComboBox();
        txt_Items_Attribute1Value = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_Items_Attribute2 = new javax.swing.JComboBox();
        txt_Items_Attribute2Value = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_Items_Save = new javax.swing.JButton();
        btn_Items_Add = new javax.swing.JButton();
        btn_Items_Delete = new javax.swing.JButton();
        txt_Items_Icon = new javax.swing.JTextField();
        lbl_Items_Icon = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Items_Id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane2.setViewportView(lst_Accounts_AccountList);

        jLabel1.setText("Accounts");

        jLabel2.setText("Account Name");

        txt_Accounts_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Accounts_NameActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        cbx_Accounts_Admin.setText("Admin Account");

        btn_Accounts_Save.setText("Save");
        btn_Accounts_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Accounts_SaveActionPerformed(evt);
            }
        });

        btn_Accounts_Delete.setText("Del");
        btn_Accounts_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Accounts_DeleteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lst_Accounts_Characters);

        jLabel4.setText("Characters");

        btn_Accounts_ViewCharacter.setText("View");

        btn_Accounts_DeleteCharacter.setText("Del");

        jLabel13.setText("Id");

        txt_Accounts_Id.setEditable(false);
        txt_Accounts_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Accounts_IdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_AccountsLayout = new javax.swing.GroupLayout(pnl_Accounts);
        pnl_Accounts.setLayout(pnl_AccountsLayout);
        pnl_AccountsLayout.setHorizontalGroup(
            pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(cbx_Accounts_Admin)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AccountsLayout.createSequentialGroup()
                                    .addComponent(btn_Accounts_Save)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Accounts_Delete))
                                .addComponent(txt_Accounts_Password)
                                .addComponent(txt_Accounts_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(txt_Accounts_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                                .addComponent(btn_Accounts_ViewCharacter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(btn_Accounts_DeleteCharacter))))
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(txt_Accounts_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_AccountsLayout.setVerticalGroup(
            pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Accounts_DeleteCharacter))
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btn_Accounts_ViewCharacter))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Accounts_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Accounts_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Accounts_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_Accounts_Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Accounts_Save)
                            .addComponent(btn_Accounts_Delete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Accounts_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        tpnl_MainPanel.addTab("Accounts", pnl_Accounts);

        jScrollPane4.setViewportView(lst_Characters_CharacterList);

        txt_Characters_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Characters_SearchActionPerformed(evt);
            }
        });

        jLabel14.setText("Account Id");

        jLabel15.setText("Id");

        txt_Characters_Id.setEditable(false);

        lbl_Characters_Name.setText("Name");

        jLabel16.setText("Race");

        jLabel17.setText("Class");

        jLabel18.setText("Id");

        lbl_WeaponName.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponName.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponName.setPreferredSize(new java.awt.Dimension(170, 16));

        lbl_WeaponAttribute1.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute1.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute1.setName(""); // NOI18N
        lbl_WeaponAttribute1.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute1.setRequestFocusEnabled(false);

        lbl_WeaponAttribute2.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute2.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute2.setName(""); // NOI18N
        lbl_WeaponAttribute2.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_WeaponAttribute2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout weaponLayout = new javax.swing.GroupLayout(weapon);
        weapon.setLayout(weaponLayout);
        weaponLayout.setHorizontalGroup(
            weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Characters_weaponId, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(weaponLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(weaponLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_WeaponName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(weaponLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_WeaponAttribute2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbl_WeaponAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        weaponLayout.setVerticalGroup(
            weaponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Characters_weaponId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_WeaponName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_WeaponAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_WeaponAttribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tpnl_Gear.addTab("Weapon", weapon);

        jLabel19.setText("Id");

        lbl_ChestName.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_ChestName.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_ChestName.setPreferredSize(new java.awt.Dimension(170, 16));

        lbl_ChestAttribute1.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute1.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute1.setName(""); // NOI18N
        lbl_ChestAttribute1.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute1.setRequestFocusEnabled(false);

        lbl_ChestAttribute2.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute2.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute2.setName(""); // NOI18N
        lbl_ChestAttribute2.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_ChestAttribute2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Characters_ChestId, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ChestName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ChestAttribute2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbl_ChestAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Characters_ChestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ChestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ChestAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ChestAttribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tpnl_Gear.addTab("Chest", jPanel1);

        jLabel20.setText("Id");

        lbl_LegsName.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_LegsName.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_LegsName.setPreferredSize(new java.awt.Dimension(170, 16));

        lbl_LegsAttribute1.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute1.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute1.setName(""); // NOI18N
        lbl_LegsAttribute1.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute1.setRequestFocusEnabled(false);

        lbl_LegsAttribute2.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute2.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute2.setName(""); // NOI18N
        lbl_LegsAttribute2.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_LegsAttribute2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Characters_LegsId, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_LegsName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_LegsAttribute2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbl_LegsAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Characters_LegsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LegsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_LegsAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_LegsAttribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tpnl_Gear.addTab("Legs", jPanel2);

        jLabel21.setText("Id");

        lbl_BootsName.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_BootsName.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_BootsName.setPreferredSize(new java.awt.Dimension(170, 16));

        lbl_BootsAttribute1.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute1.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute1.setName(""); // NOI18N
        lbl_BootsAttribute1.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute1.setRequestFocusEnabled(false);

        lbl_BootsAttribute2.setMaximumSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute2.setMinimumSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute2.setName(""); // NOI18N
        lbl_BootsAttribute2.setPreferredSize(new java.awt.Dimension(170, 16));
        lbl_BootsAttribute2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout BootsLayout = new javax.swing.GroupLayout(Boots);
        Boots.setLayout(BootsLayout);
        BootsLayout.setHorizontalGroup(
            BootsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BootsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BootsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Characters_BootsId, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(BootsLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BootsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(BootsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_BootsName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(BootsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(BootsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_BootsAttribute2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbl_BootsAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        BootsLayout.setVerticalGroup(
            BootsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BootsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Characters_BootsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_BootsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_BootsAttribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_BootsAttribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tpnl_Gear.addTab("Boots", Boots);

        btn_Characters_Save.setText("Save");

        btn_Characters_Delete.setText("Del");

        javax.swing.GroupLayout pnl_CharactersLayout = new javax.swing.GroupLayout(pnl_Characters);
        pnl_Characters.setLayout(pnl_CharactersLayout);
        pnl_CharactersLayout.setHorizontalGroup(
            pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CharactersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_Character_AccountId)
                    .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txt_Characters_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_CharactersLayout.createSequentialGroup()
                        .addComponent(btn_Characters_Save)
                        .addGap(59, 59, 59)
                        .addComponent(btn_Characters_Delete))
                    .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(txt_Characters_Id)
                            .addComponent(lbl_Characters_Name)
                            .addComponent(txt_Characters_Name)
                            .addComponent(jLabel16)
                            .addComponent(cmb_Characters_Race, 0, 161, Short.MAX_VALUE))
                        .addComponent(jLabel17)
                        .addComponent(cmb_Characters_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnl_Gear)
                .addContainerGap())
        );
        pnl_CharactersLayout.setVerticalGroup(
            pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CharactersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CharactersLayout.createSequentialGroup()
                        .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Character_AccountId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Characters_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_CharactersLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Characters_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(pnl_CharactersLayout.createSequentialGroup()
                                .addComponent(lbl_Characters_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Characters_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_Characters_Race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_Characters_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Characters_Save)
                                    .addComponent(btn_Characters_Delete))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnl_CharactersLayout.createSequentialGroup()
                        .addComponent(tpnl_Gear, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tpnl_MainPanel.addTab("Characters", pnl_Characters);

        cmb_Items_SlotList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_Items_SlotListActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lst_Items_ItemList);

        jLabel5.setText("Name");

        jLabel6.setText("Slot type");

        jLabel7.setText("Id");

        jLabel8.setText("Value");

        jLabel9.setText("Attribute 2");

        jLabel10.setText("Value");

        btn_Items_Save.setText("Save");
        btn_Items_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Items_SaveActionPerformed(evt);
            }
        });

        btn_Items_Add.setText("Add");
        btn_Items_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Items_AddActionPerformed(evt);
            }
        });

        btn_Items_Delete.setText("Delete");
        btn_Items_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Items_DeleteActionPerformed(evt);
            }
        });

        lbl_Items_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unknown.png"))); // NOI18N
        lbl_Items_Icon.setVerifyInputWhenFocusTarget(false);

        jLabel12.setText("Icon");

        jLabel11.setText("Attribute 1");

        txt_Items_Id.setEditable(false);

        javax.swing.GroupLayout pnl_ItemsLayout = new javax.swing.GroupLayout(pnl_Items);
        pnl_Items.setLayout(pnl_ItemsLayout);
        pnl_ItemsLayout.setHorizontalGroup(
            pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cmb_Items_SlotList, 0, 151, Short.MAX_VALUE)
                    .addComponent(txt_Items_Search))
                .addGap(18, 18, 18)
                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ItemsLayout.createSequentialGroup()
                        .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Items_Icon)
                            .addComponent(txt_Items_Name)
                            .addComponent(cmb_Items_Slot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addGroup(pnl_ItemsLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(lbl_Items_Icon)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(cmb_Items_Attribute1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ItemsLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Items_Attribute1Value, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(cmb_Items_Attribute2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ItemsLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Items_Attribute2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_Items_Id)
                            .addComponent(jLabel11)))
                    .addGroup(pnl_ItemsLayout.createSequentialGroup()
                        .addComponent(btn_Items_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Items_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Items_Delete)))
                .addContainerGap())
        );
        pnl_ItemsLayout.setVerticalGroup(
            pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_Items_SlotList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ItemsLayout.createSequentialGroup()
                        .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Items_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Items_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_Items_Slot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Items_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Items_Icon))
                            .addGroup(pnl_ItemsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cmb_Items_Attribute1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Items_Attribute1Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_Items_Attribute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Items_Attribute2Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Items_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Items_Save)
                    .addComponent(btn_Items_Add)
                    .addComponent(btn_Items_Delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnl_MainPanel.addTab("Items", pnl_Items);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnl_MainPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnl_MainPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Accounts_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Accounts_DeleteActionPerformed
        if(_selectedAccount == null){
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete " + _selectedAccount.getName() + " ?", "Warning" , JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            
            if (Services.CharacterServices.GetAllChactersOfAccount(_selectedAccount.getId()).size() != 0) {
                JOptionPane.showMessageDialog(this,"Can't delete account that has characters.");
                return;
            }
            else{
                Services.AccountServices.DeleteAccount(_selectedAccount);
                ResetAccountPanel();
            }
 
        }
    }//GEN-LAST:event_btn_Accounts_DeleteActionPerformed

    private void btn_Accounts_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Accounts_SaveActionPerformed
        if(_selectedAccount == null){
            return;
        }
        
        _selectedAccount.setName(txt_Accounts_Name.getText());
        _selectedAccount.setPassword(txt_Accounts_Password.getText());
        _selectedAccount.setAdmin(cbx_Accounts_Admin.isSelected());
        Services.AccountServices.UpdateAccount(_selectedAccount);
        JOptionPane.showMessageDialog(this,"Account updated.");
 
        lst_Accounts_AccountList.setListData(Services.AccountServices.GetAllAccounts().toArray());
        
        
    }//GEN-LAST:event_btn_Accounts_SaveActionPerformed

    private void btn_Items_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Items_SaveActionPerformed
        _selectedItem.setName(txt_Items_Name.getText());
        _selectedItem.setSlot((DAL.Slot) cmb_Items_Slot.getSelectedItem());
        _selectedItem.setIconPath(txt_Items_Icon.getText());
        _selectedItem.setAttribute1((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem());
        _selectedItem.setAttribute1value(Integer.parseInt(txt_Items_Attribute1Value.getText()));
        if (((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem()).getName().equals("None")) {
            _selectedItem.setAttribute2(null);
            _selectedItem.setAttribute2value(0);
        }
        else{
            _selectedItem.setAttribute2((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem());
            _selectedItem.setAttribute2value(Integer.parseInt(txt_Items_Attribute2Value.getText()));
        }
        
        Services.ItemServices.UpdateItem(_selectedItem);
        JOptionPane.showMessageDialog(this,"Item updated.");

        
        UpdateItemlist();
    }//GEN-LAST:event_btn_Items_SaveActionPerformed

    private void btn_Items_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Items_AddActionPerformed
        DAL.Item item = new Item();
        item.setName(txt_Items_Name.getText());
        item.setSlot((DAL.Slot) cmb_Items_Slot.getSelectedItem());
        item.setIconPath(txt_Items_Icon.getText());
        item.setAttribute1((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem());
        item.setAttribute1value(Integer.parseInt(txt_Items_Attribute1Value.getText()));
        if (((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem()).getName().equals("None")) {
            item.setAttribute2(null);
            item.setAttribute2value(0);
        }
        else{
            item.setAttribute2((DAL.Attribute)cmb_Items_Attribute1.getSelectedItem());
            item.setAttribute2value(Integer.parseInt(txt_Items_Attribute2Value.getText()));
        }
        
        try {
            Services.ItemServices.InsertItem(item);
        } catch (UIException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this,"Item "+ item.getName() +" added.");
        UpdateItemlist();
    }//GEN-LAST:event_btn_Items_AddActionPerformed

    private void btn_Items_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Items_DeleteActionPerformed
        Services.ItemServices.DeleteCharacter(_selectedItem);
        UpdateItemlist();
        ResetItemPanel();
    }//GEN-LAST:event_btn_Items_DeleteActionPerformed

    private void cmb_Items_SlotListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_Items_SlotListActionPerformed
        //lst_Items_ItemList.removeAll();
        
        UpdateItemlist();
    }//GEN-LAST:event_cmb_Items_SlotListActionPerformed

    private void txt_Accounts_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Accounts_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Accounts_NameActionPerformed

    private void txt_Accounts_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Accounts_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Accounts_IdActionPerformed

    private void txt_Characters_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Characters_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Characters_SearchActionPerformed

    private void ResetAccountPanel(){
        _selectedAccount = null;
        txt_Accounts_Name.setText("");
        txt_Accounts_Password.setText("");
        cbx_Accounts_Admin.setSelected(false);
        //lst_Characeters.removeAll();
        lst_Accounts_AccountList.setListData(Services.AccountServices.GetAllAccounts().toArray());
        txt_Accounts_Id.setText("");
    }
    
    private void ResetItemPanel(){
        _selectedItem = null;
        txt_Items_Name.setText("");
        txt_Items_Icon.setText("");
        cmb_Items_Slot.setSelectedIndex(0);
        cmb_Items_Attribute1.setSelectedIndex(0);
        txt_Items_Attribute1Value.setText("");
        cmb_Items_Attribute2.setSelectedIndex(0);
        txt_Items_Attribute2Value.setText("");
        txt_Items_Id.setText("");
    }
    
    private void ResetCharacterPanel(){
        txt_Characters_Id.setText("");
        txt_Characters_Name.setText("");
        txt_Characters_weaponId.setText("");
        lbl_WeaponName.setText("");
        lbl_WeaponAttribute1.setText("");
        lbl_WeaponAttribute2.setText("");
        txt_Characters_ChestId.setText("");
        lbl_ChestName.setText("");
        lbl_ChestAttribute1.setText("");
        lbl_ChestAttribute2.setText("");
        txt_Characters_LegsId.setText("");
        lbl_LegsName.setText("");
        lbl_LegsAttribute1.setText("");
        lbl_LegsAttribute2.setText("");
        txt_Characters_BootsId.setText("");
        lbl_BootsName.setText("");
        lbl_BootsAttribute1.setText("");
        lbl_BootsAttribute2.setText("");
    }
    
    private void InitAccount(){
        lst_Accounts_AccountList.setListData(Services.AccountServices.GetAllAccounts().toArray());
        lst_Accounts_AccountList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if(lst_Accounts_AccountList.getSelectedValue() == null){
                    return;
                }
                _selectedAccount = (DAL.Account) lst_Accounts_AccountList.getSelectedValue();
                txt_Accounts_Name.setText(_selectedAccount.getName());
                txt_Accounts_Password.setText(_selectedAccount.getPassword());
                cbx_Accounts_Admin.setSelected(_selectedAccount.isAdmin());
                txt_Accounts_Id.setText(""+_selectedAccount.getId());
                
                lst_Accounts_Characters.setListData(Services.CharacterServices.GetAllChactersOfAccount(_selectedAccount.getId()).toArray());
            }
        });
        
        txt_Accounts_Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                lst_Accounts_AccountList.setListData(Services.AccountServices.GetAccountsLike(txt_Accounts_Search.getText()).toArray()); ;
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                lst_Accounts_AccountList.setListData(Services.AccountServices.GetAccountsLike(txt_Accounts_Search.getText()).toArray()); ;
            }
        });
    }
    
    private void InitItem(){
        Slot slot = new Slot("All");
        cmb_Items_SlotList.addItem(slot);
        
        if(Services.MiscServices.getSlotList() == null){
            Services.MiscServices.LoadSlotData();
        }
        for (DAL.Slot s : Services.MiscServices.getSlotList()) {
            cmb_Items_SlotList.addItem(s);
            cmb_Items_Slot.addItem(s);
        }

        DAL.Attribute attribute = new DAL.Attribute("None");
        cmb_Items_Attribute2.addItem(attribute);
        for (DAL.Attribute att : Services.MiscServices.getAttributeList()) {
            cmb_Items_Attribute1.addItem(att);
            cmb_Items_Attribute2.addItem(att);
        }
        
        lst_Items_ItemList.setListData(Services.ItemServices.getLootList().toArray());
        
        
        lst_Items_ItemList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if(lst_Items_ItemList.getSelectedValue() == null){
                    return;
                }
                _selectedItem = (DAL.Item) lst_Items_ItemList.getSelectedValue();
                txt_Items_Name.setText(_selectedItem.getName());
                txt_Items_Attribute1Value.setText("" + _selectedItem.getAttribute1value());
                txt_Items_Attribute2Value.setText("" + _selectedItem.getAttribute2value());
                for (int i = 0; i < cmb_Items_Slot.getItemCount(); i++) {
                    DAL.Slot sl = (DAL.Slot)cmb_Items_Slot.getItemAt(i);
                    if(sl.getId() == _selectedItem.getSlot().getId()){
                       cmb_Items_Slot.setSelectedIndex(i);
                    }
                }
                
                for (int i = 0; i < cmb_Items_Attribute1.getItemCount(); i++) {
                    DAL.Attribute att = (DAL.Attribute)cmb_Items_Attribute1.getItemAt(i);
                    if (att.getId() == _selectedItem.getAttribute1().getId()) {
                        cmb_Items_Attribute1.setSelectedIndex(i);
                    }
                }
                
                if(_selectedItem.getAttribute2() == null){
                    cmb_Items_Attribute2.setSelectedIndex(0);
                }else{
                    for (int i = 1; i < cmb_Items_Attribute2.getItemCount(); i++) {
                    
                        DAL.Attribute att = (DAL.Attribute)cmb_Items_Attribute2.getItemAt(i);
                        if (att.getId() == _selectedItem.getAttribute2().getId()) {
                            cmb_Items_Attribute2.setSelectedIndex(i);
                        }
                    }
                }
                
                txt_Items_Icon.setText(_selectedItem.getIconPath());
                GameWindow gmw = new GameWindow();
                gmw.ChangeIcon(lbl_Items_Icon, _selectedItem.getIconPath());
                
                txt_Items_Id.setText(""+_selectedItem.getId());
            }
        });
        
        txt_Items_Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                UpdateItemlist();
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                UpdateItemlist();
            }
        });
        
        txt_Items_Icon.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                GameWindow gmw = new GameWindow();
                gmw.ChangeIcon(lbl_Items_Icon, txt_Items_Icon.getText());
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                GameWindow gmw = new GameWindow();
                gmw.ChangeIcon(lbl_Items_Icon, txt_Items_Icon.getText());
            }
        });
    }
    
    private void InitCharacter(){
        lst_Characters_CharacterList.setListData(Services.CharacterServices.GetCharacterLike("").toArray());
        for (DAL.Race r : Services.MiscServices.getRaceList()) {
            cmb_Characters_Race.addItem(r);
        }
        for (DAL.Charclass c : Services.MiscServices.getClassList()) {
            cmb_Characters_Class.addItem(c);
        }
        
        txt_Characters_Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                lst_Characters_CharacterList.setListData(Services.CharacterServices.GetCharacterLike(txt_Characters_Search.getText()).toArray());
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                lst_Characters_CharacterList.setListData(Services.CharacterServices.GetCharacterLike(txt_Characters_Search.getText()).toArray());
            }
        });
        
        txt_Character_AccountId.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                if(txt_Character_AccountId.getText().equals("")){
                    lst_Characters_CharacterList.setListData(Services.CharacterServices.GetCharacterLike("").toArray());
                }
                else{
                    try {
                        int id = Integer.parseInt(txt_Character_AccountId.getText());
                        lst_Characters_CharacterList.setListData(Services.CharacterServices.GetAllChactersOfAccount(id).toArray());
                    } catch (Exception e) {
                        return;
                    }
                }
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                if(txt_Character_AccountId.getText().equals("")){
                    lst_Characters_CharacterList.setListData(Services.CharacterServices.GetCharacterLike("").toArray());
                }
                else{
                    try {
                        int id = Integer.parseInt(txt_Character_AccountId.getText());
                        lst_Characters_CharacterList.setListData(Services.CharacterServices.GetAllChactersOfAccount(id).toArray());
                    } catch (Exception e) {
                        return;
                    }
                }
                
            }
        });
        
        lst_Characters_CharacterList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ResetCharacterPanel();
                if(lst_Characters_CharacterList.getSelectedValue() == null){
                    return;
                }
                _selectedCharacter = (DAL.Character) lst_Characters_CharacterList.getSelectedValue();
                
                txt_Characters_Id.setText(""+_selectedCharacter.getId());
                txt_Characters_Name.setText(_selectedCharacter.getName());
                
                for (int i = 0; i < cmb_Characters_Race.getItemCount(); i++) {
                    DAL.Race sl = (DAL.Race)cmb_Characters_Race.getItemAt(i);
                    if(sl.getId() == _selectedCharacter.getRace().getId()){
                       cmb_Characters_Race.setSelectedIndex(i);
                    }
                }
                
                for (int i = 0; i < cmb_Characters_Class.getItemCount(); i++) {
                    DAL.Charclass sl = (DAL.Charclass)cmb_Characters_Class.getItemAt(i);
                    if(sl.getId() == _selectedCharacter.getCharclass().getId()){
                       cmb_Characters_Class.setSelectedIndex(i);
                    }
                }
                
                if (_selectedCharacter.getItemByWeaponItemId() != null) {
                    DAL.Item weapon = Services.ItemServices.GetItemById(_selectedCharacter.getItemByWeaponItemId().getId());
                    txt_Characters_weaponId.setText(""+weapon.getId());
                    lbl_WeaponName.setText(weapon.getName());
                    lbl_WeaponAttribute1.setText("+" + weapon.getAttribute1value() + " " + weapon.getAttribute1().getName());
                    if (weapon.getAttribute2() != null) {
                        lbl_WeaponAttribute2.setText("+" + weapon.getAttribute2value() + " " + weapon.getAttribute2().getName());
                    }
                }
                
                if (_selectedCharacter.getItemByChestItemId()!= null) {
                    DAL.Item chest = Services.ItemServices.GetItemById(_selectedCharacter.getItemByChestItemId().getId());
                    txt_Characters_ChestId.setText(""+chest.getId());
                    lbl_ChestName.setText(chest.getName());
                    lbl_ChestAttribute1.setText("+" + chest.getAttribute1value() + " " + chest.getAttribute1().getName());
                    if (chest.getAttribute2() != null) {
                        lbl_ChestAttribute2.setText("+" + chest.getAttribute2value() + " " + chest.getAttribute2().getName());
                    }
                }
                
                if (_selectedCharacter.getItemByLegsItemId()!= null) {
                    DAL.Item legs = Services.ItemServices.GetItemById(_selectedCharacter.getItemByLegsItemId().getId());
                    txt_Characters_LegsId.setText(""+legs.getId());
                    lbl_LegsName.setText(legs.getName());
                    lbl_LegsAttribute1.setText("+" + legs.getAttribute1value() + " " + legs.getAttribute1().getName());
                    if (legs.getAttribute2() != null) {
                        lbl_LegsAttribute2.setText("+" + legs.getAttribute2value() + " " + legs.getAttribute2().getName());
                    }
                }
                
                if (_selectedCharacter.getItemByBootsItemId()!= null) {
                    DAL.Item boots = Services.ItemServices.GetItemById(_selectedCharacter.getItemByBootsItemId().getId());
                    txt_Characters_BootsId.setText(""+boots.getId());
                    lbl_BootsName.setText(boots.getName());
                    lbl_BootsAttribute1.setText("+" + boots.getAttribute1value() + " " + boots.getAttribute1().getName());
                    if (boots.getAttribute2() != null) {
                        lbl_BootsAttribute2.setText("+" + boots.getAttribute2value() + " " + boots.getAttribute2().getName());
                    }
                }
                
                /*_selectedItem = (DAL.Item) lst_Items_ItemList.getSelectedValue();
                txt_Items_Name.setText(_selectedItem.getName());
                txt_Items_Attribute1Value.setText("" + _selectedItem.getAttribute1value());
                txt_Items_Attribute2Value.setText("" + _selectedItem.getAttribute2value());
                for (int i = 0; i < cmb_Items_Slot.getItemCount(); i++) {
                    DAL.Slot sl = (DAL.Slot)cmb_Items_Slot.getItemAt(i);
                    if(sl.getId() == _selectedItem.getSlot().getId()){
                       cmb_Items_Slot.setSelectedIndex(i);
                    }
                }
                
                for (int i = 0; i < cmb_Items_Attribute1.getItemCount(); i++) {
                    DAL.Attribute att = (DAL.Attribute)cmb_Items_Attribute1.getItemAt(i);
                    if (att.getId() == _selectedItem.getAttribute1().getId()) {
                        cmb_Items_Attribute1.setSelectedIndex(i);
                    }
                }
                
                if(_selectedItem.getAttribute2() == null){
                    cmb_Items_Attribute2.setSelectedIndex(0);
                }else{
                    for (int i = 1; i < cmb_Items_Attribute2.getItemCount(); i++) {
                    
                        DAL.Attribute att = (DAL.Attribute)cmb_Items_Attribute2.getItemAt(i);
                        if (att.getId() == _selectedItem.getAttribute2().getId()) {
                            cmb_Items_Attribute2.setSelectedIndex(i);
                        }
                    }
                }
                
                txt_Items_Icon.setText(_selectedItem.getIconPath());
                GameWindow gmw = new GameWindow();
                gmw.ChangeIcon(lbl_Items_Icon, _selectedItem.getIconPath());
                
                txt_Items_Id.setText(""+_selectedItem.getId());*/
            }
        });
    }
    
    private void UpdateItemlist(){
        DAL.Slot slot = (DAL.Slot)cmb_Items_SlotList.getSelectedItem();
        if (slot.getName().equals("All")) { 
            lst_Items_ItemList.setListData(Services.ItemServices.GetAccountsLike(txt_Items_Search.getText(), null).toArray());
        }else{
            lst_Items_ItemList.setListData(Services.ItemServices.GetAccountsLike(txt_Items_Search.getText(), slot).toArray());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boots;
    private javax.swing.JButton btn_Accounts_Delete;
    private javax.swing.JButton btn_Accounts_DeleteCharacter;
    private javax.swing.JButton btn_Accounts_Save;
    private javax.swing.JButton btn_Accounts_ViewCharacter;
    private javax.swing.JButton btn_Characters_Delete;
    private javax.swing.JButton btn_Characters_Save;
    private javax.swing.JButton btn_Items_Add;
    private javax.swing.JButton btn_Items_Delete;
    private javax.swing.JButton btn_Items_Save;
    private javax.swing.JCheckBox cbx_Accounts_Admin;
    private javax.swing.JComboBox cmb_Characters_Class;
    private javax.swing.JComboBox cmb_Characters_Race;
    private javax.swing.JComboBox cmb_Items_Attribute1;
    private javax.swing.JComboBox cmb_Items_Attribute2;
    private javax.swing.JComboBox cmb_Items_Slot;
    private javax.swing.JComboBox cmb_Items_SlotList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_BootsAttribute1;
    private javax.swing.JLabel lbl_BootsAttribute2;
    private javax.swing.JLabel lbl_BootsName;
    private javax.swing.JLabel lbl_Characters_Name;
    private javax.swing.JLabel lbl_ChestAttribute1;
    private javax.swing.JLabel lbl_ChestAttribute2;
    private javax.swing.JLabel lbl_ChestName;
    private javax.swing.JLabel lbl_Items_Icon;
    private javax.swing.JLabel lbl_LegsAttribute1;
    private javax.swing.JLabel lbl_LegsAttribute2;
    private javax.swing.JLabel lbl_LegsName;
    private javax.swing.JLabel lbl_WeaponAttribute1;
    private javax.swing.JLabel lbl_WeaponAttribute2;
    private javax.swing.JLabel lbl_WeaponName;
    private javax.swing.JList lst_Accounts_AccountList;
    private javax.swing.JList lst_Accounts_Characters;
    private javax.swing.JList lst_Characters_CharacterList;
    private javax.swing.JList lst_Items_ItemList;
    private javax.swing.JPanel pnl_Accounts;
    private javax.swing.JPanel pnl_Characters;
    private javax.swing.JPanel pnl_Items;
    private javax.swing.JTabbedPane tpnl_Gear;
    private javax.swing.JTabbedPane tpnl_MainPanel;
    private javax.swing.JTextField txt_Accounts_Id;
    private javax.swing.JTextField txt_Accounts_Name;
    private javax.swing.JTextField txt_Accounts_Password;
    private javax.swing.JTextField txt_Accounts_Search;
    private javax.swing.JTextField txt_Character_AccountId;
    private javax.swing.JTextField txt_Characters_BootsId;
    private javax.swing.JTextField txt_Characters_ChestId;
    private javax.swing.JTextField txt_Characters_Id;
    private javax.swing.JTextField txt_Characters_LegsId;
    private javax.swing.JTextField txt_Characters_Name;
    private javax.swing.JTextField txt_Characters_Search;
    private javax.swing.JTextField txt_Characters_weaponId;
    private javax.swing.JTextField txt_Items_Attribute1Value;
    private javax.swing.JTextField txt_Items_Attribute2Value;
    private javax.swing.JTextField txt_Items_Icon;
    private javax.swing.JTextField txt_Items_Id;
    private javax.swing.JTextField txt_Items_Name;
    private javax.swing.JTextField txt_Items_Search;
    private javax.swing.JPanel weapon;
    // End of variables declaration//GEN-END:variables
}
