/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author LanceDH
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
        
        lst_Accounts.setListData(Services.AccountServices.GetAllAccounts().toArray());
        lst_Accounts.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if(lst_Accounts.getSelectedValue() == null){
                    return;
                }
                DAL.Account acc = (DAL.Account) lst_Accounts.getSelectedValue();
                txt_Name.setText(acc.getName());
                txt_Password.setText(acc.getPassword());
                cbx_Admin.setSelected(acc.isAdmin());
                
                lst_Characeters.setListData(Services.CharacterServices.GetAllChactersOfAccount(acc.getId()).toArray());
            }
        });
        
        
        txt_Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {}
       
            @Override
            @SuppressWarnings("empty-statement")
            public void insertUpdate(DocumentEvent de) {
                lst_Accounts.setListData(Services.AccountServices.GetAccountsLike(txt_Search.getText()).toArray()); ;
            }
            @Override
            @SuppressWarnings("empty-statement")
            public void removeUpdate(DocumentEvent de) {
                lst_Accounts.setListData(Services.AccountServices.GetAccountsLike(txt_Search.getText()).toArray()); ;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnl_MainPanel = new javax.swing.JTabbedPane();
        pnl_Accounts = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Accounts = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JTextField();
        cbx_Admin = new javax.swing.JCheckBox();
        btn_SaveAccount = new javax.swing.JButton();
        btn_DeleteAccount = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_Characeters = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        btn_ViewCharaceter = new javax.swing.JButton();
        btn_DeleteCharacter = new javax.swing.JButton();
        pnl_Characters = new javax.swing.JPanel();
        pnl_Items = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(lst_Accounts);

        jLabel1.setText("Accounts");

        jLabel2.setText("Account Name");

        jLabel3.setText("Password");

        cbx_Admin.setText("Admin Account");

        btn_SaveAccount.setText("Save");

        btn_DeleteAccount.setText("Del");

        jScrollPane3.setViewportView(lst_Characeters);

        jLabel4.setText("Characters");

        btn_ViewCharaceter.setText("View");

        btn_DeleteCharacter.setText("Del");

        javax.swing.GroupLayout pnl_AccountsLayout = new javax.swing.GroupLayout(pnl_Accounts);
        pnl_Accounts.setLayout(pnl_AccountsLayout);
        pnl_AccountsLayout.setHorizontalGroup(
            pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(cbx_Admin)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(btn_SaveAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btn_DeleteAccount))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(btn_ViewCharaceter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_DeleteCharacter))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_Password)
                    .addComponent(txt_Name))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pnl_AccountsLayout.setVerticalGroup(
            pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_AccountsLayout.createSequentialGroup()
                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_Admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SaveAccount)
                            .addComponent(btn_DeleteAccount))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_AccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ViewCharaceter)
                    .addComponent(btn_DeleteCharacter))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tpnl_MainPanel.addTab("Accounts", pnl_Accounts);

        javax.swing.GroupLayout pnl_CharactersLayout = new javax.swing.GroupLayout(pnl_Characters);
        pnl_Characters.setLayout(pnl_CharactersLayout);
        pnl_CharactersLayout.setHorizontalGroup(
            pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        pnl_CharactersLayout.setVerticalGroup(
            pnl_CharactersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        tpnl_MainPanel.addTab("Characters", pnl_Characters);

        javax.swing.GroupLayout pnl_ItemsLayout = new javax.swing.GroupLayout(pnl_Items);
        pnl_Items.setLayout(pnl_ItemsLayout);
        pnl_ItemsLayout.setHorizontalGroup(
            pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        pnl_ItemsLayout.setVerticalGroup(
            pnl_ItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        tpnl_MainPanel.addTab("Items", pnl_Items);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnl_MainPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpnl_MainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteAccount;
    private javax.swing.JButton btn_DeleteCharacter;
    private javax.swing.JButton btn_SaveAccount;
    private javax.swing.JButton btn_ViewCharaceter;
    private javax.swing.JCheckBox cbx_Admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lst_Accounts;
    private javax.swing.JList lst_Characeters;
    private javax.swing.JPanel pnl_Accounts;
    private javax.swing.JPanel pnl_Characters;
    private javax.swing.JPanel pnl_Items;
    private javax.swing.JTabbedPane tpnl_MainPanel;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_Search;
    // End of variables declaration//GEN-END:variables
}
