/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.swing.JLabel;

/**
 *
 * @author 11627
 */
public class CharacterCreateWindow extends javax.swing.JPanel {

    GameWindow _parent;
    
    /**
     * Creates new form CharacterCreateWindow
     */
    public CharacterCreateWindow(GameWindow parent) {
        initComponents();
        _parent = parent;
        
        //lbl_SelectRace.setBounds(new Rectangle(lbl_RaceHuman.getLocation(), lbl_SelectRace.getPreferredSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_ClassRogue = new javax.swing.JLabel();
        lbl_ClassWarrior = new javax.swing.JLabel();
        lbl_ClassMage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_RaceElf = new javax.swing.JLabel();
        lbl_RaceHuman = new javax.swing.JLabel();
        lbl_RaceOrc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AccountName");

        jToggleButton1.setText("jToggleButton1");

        lbl_ClassRogue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Class_Rogue.png"))); // NOI18N
        lbl_ClassRogue.setName("3"); // NOI18N

        lbl_ClassWarrior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/class_Warrior.png"))); // NOI18N
        lbl_ClassWarrior.setName("1"); // NOI18N

        lbl_ClassMage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Class_Mage.png"))); // NOI18N
        lbl_ClassMage.setName("2"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Class");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ClassWarrior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ClassMage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ClassRogue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_ClassMage)
                    .addComponent(lbl_ClassWarrior)
                    .addComponent(lbl_ClassRogue))
                .addGap(20, 20, 20))
        );

        lbl_RaceElf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Race_Elf.png"))); // NOI18N
        lbl_RaceElf.setName("2"); // NOI18N
        lbl_RaceElf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectRace(evt);
            }
        });

        lbl_RaceHuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Race_Human.png"))); // NOI18N
        lbl_RaceHuman.setName("0"); // NOI18N
        lbl_RaceHuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectRace(evt);
            }
        });

        lbl_RaceOrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Race_Orc.png"))); // NOI18N
        lbl_RaceOrc.setName("1"); // NOI18N
        lbl_RaceOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectRace(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Race");
        jLabel6.setMaximumSize(new java.awt.Dimension(61, 29));
        jLabel6.setMinimumSize(new java.awt.Dimension(61, 29));
        jLabel6.setPreferredSize(new java.awt.Dimension(61, 29));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_RaceHuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_RaceOrc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_RaceElf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_RaceOrc)
                    .addComponent(lbl_RaceHuman)
                    .addComponent(lbl_RaceElf))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectRace(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectRace
        System.out.println(evt.getComponent().getName());
        ChangeSelectedRaceIcon(Integer.parseInt(evt.getComponent().getName()));
    }//GEN-LAST:event_SelectRace

    private void ChangeSelectedRaceIcon(int nr){
        _parent.ChangeIcon(lbl_RaceHuman, Services.MiscServices.RaceList.get(0).getIconPath());
        _parent.ChangeIcon(lbl_RaceOrc, Services.MiscServices.RaceList.get(1).getIconPath());
        _parent.ChangeIcon(lbl_RaceElf, Services.MiscServices.RaceList.get(2).getIconPath());
                                
        
        JLabel lbl = null;
        switch(nr){
            case 0:
                lbl = lbl_RaceHuman;
                break;
            case 1:
                lbl = lbl_RaceOrc;
                break;
            case 2:
                lbl = lbl_RaceElf;
                break;
        }
        
        _parent.ChangeIcon(lbl, Services.MiscServices.RaceList.get(nr).getIconPath()+"_Selected");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_ClassMage;
    private javax.swing.JLabel lbl_ClassRogue;
    private javax.swing.JLabel lbl_ClassWarrior;
    private javax.swing.JLabel lbl_RaceElf;
    private javax.swing.JLabel lbl_RaceHuman;
    private javax.swing.JLabel lbl_RaceOrc;
    // End of variables declaration//GEN-END:variables
}
