/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.Item;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author LanceDH
 */
public class LootPanel extends javax.swing.JPanel {

    private GameWindow _parent;
    private Item loot;
    /**
     * Creates new form LootWindow
     */
    public LootPanel(GameWindow parent) {
        initComponents();
        this._parent = parent;
        Services.ItemServices.LoadAllLoot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Test = new javax.swing.JPanel();
        lbl_CharacterName = new javax.swing.JLabel();
        btn_ChangeCharacter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_ChestIcon = new javax.swing.JLabel();
        lbl_LegsIcon = new javax.swing.JLabel();
        lbl_FeetIcon = new javax.swing.JLabel();
        lbl_WeaponIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_LootIcon = new javax.swing.JLabel();
        btn_Loot = new javax.swing.JButton();
        lbl_ItemName = new javax.swing.JLabel();
        lbl_ItemSlot = new javax.swing.JLabel();
        lbl_ItemAtt1 = new javax.swing.JLabel();
        btn_Equip = new javax.swing.JButton();
        lbl_ItemAtt2 = new javax.swing.JLabel();
        lbl_IconClass = new javax.swing.JLabel();
        lbl_IconRace = new javax.swing.JLabel();

        javax.swing.GroupLayout pnl_TestLayout = new javax.swing.GroupLayout(pnl_Test);
        pnl_Test.setLayout(pnl_TestLayout);
        pnl_TestLayout.setHorizontalGroup(
            pnl_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_TestLayout.setVerticalGroup(
            pnl_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbl_CharacterName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CharacterName.setToolTipText("");
        lbl_CharacterName.setMaximumSize(new java.awt.Dimension(5, 14));
        lbl_CharacterName.setMinimumSize(new java.awt.Dimension(5, 14));
        lbl_CharacterName.setPreferredSize(new java.awt.Dimension(5, 14));

        btn_ChangeCharacter.setText("Back");
        btn_ChangeCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeCharacterActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(137, 210));
        jPanel1.setMinimumSize(new java.awt.Dimension(137, 210));

        lbl_ChestIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Slot-Chest.png"))); // NOI18N
        lbl_ChestIcon.setToolTipText("");

        lbl_LegsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Slot-Legs.png"))); // NOI18N
        lbl_LegsIcon.setToolTipText("");

        lbl_FeetIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Slot-Feet.png"))); // NOI18N
        lbl_FeetIcon.setToolTipText("");

        lbl_WeaponIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_WeaponIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Slot-Weapon.png"))); // NOI18N
        lbl_WeaponIcon.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_FeetIcon, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lbl_ChestIcon, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_WeaponIcon)
                .addGap(9, 9, 9)
                .addComponent(lbl_LegsIcon))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ChestIcon)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_LegsIcon)
                    .addComponent(lbl_WeaponIcon))
                .addGap(9, 9, 9)
                .addComponent(lbl_FeetIcon))
        );

        lbl_LootIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Slot-Loot.png"))); // NOI18N
        lbl_LootIcon.setToolTipText("");

        btn_Loot.setText("Loot");
        btn_Loot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LootActionPerformed(evt);
            }
        });

        lbl_ItemName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ItemName.setText("Name");

        lbl_ItemSlot.setText("Slot");

        lbl_ItemAtt1.setText("Attribute1");

        btn_Equip.setText("Equip");
        btn_Equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EquipActionPerformed(evt);
            }
        });

        lbl_ItemAtt2.setText("Attribute2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ItemAtt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ItemSlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ItemAtt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_LootIcon)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Loot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Equip, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Loot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Equip))
                    .addComponent(lbl_LootIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ItemSlot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ItemAtt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ItemAtt2)
                .addGap(16, 16, 16))
        );

        lbl_IconClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unknown_26.png"))); // NOI18N
        lbl_IconClass.setToolTipText("");
        lbl_IconClass.setMaximumSize(new java.awt.Dimension(25, 25));
        lbl_IconClass.setMinimumSize(new java.awt.Dimension(25, 25));
        lbl_IconClass.setPreferredSize(new java.awt.Dimension(25, 25));

        lbl_IconRace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unknown_26.png"))); // NOI18N
        lbl_IconRace.setToolTipText("");
        lbl_IconRace.setMaximumSize(new java.awt.Dimension(25, 25));
        lbl_IconRace.setMinimumSize(new java.awt.Dimension(25, 25));
        lbl_IconRace.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_IconRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_IconClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_CharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btn_ChangeCharacter)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_ChangeCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_CharacterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_IconClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IconRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChangeCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeCharacterActionPerformed
        Services.CharacterServices.UpdateCharacter(_parent.getActiveCharacter());
        _parent.setActiveCharacter(null);
        _parent.remove(this);
        _parent.ShowCharacterSelect();
    }//GEN-LAST:event_btn_ChangeCharacterActionPerformed

    private void btn_LootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LootActionPerformed
        Random rnd = new Random();
        loot = Services.ItemServices.getLootList().get(rnd.nextInt(Services.ItemServices.getLootList().size()));
        _parent.ChangeIcon(lbl_LootIcon, loot.getIconPath());
        lbl_ItemName.setText(loot.getName());
        lbl_ItemSlot.setText(loot.getSlot().getName());
        lbl_ItemAtt1.setText("+" + loot.getAttribute1value() + " " +loot.getAttribute1().getName());
        if(loot.getAttribute2() != null){
            lbl_ItemAtt2.setText("+" + loot.getAttribute2value() + " " +loot.getAttribute2().getName());
        }
        else{
            lbl_ItemAtt2.setText("");
        }
    }//GEN-LAST:event_btn_LootActionPerformed

    private void btn_EquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EquipActionPerformed
        //Don't allow equiping when there is no loot
        if (loot == null) {
            return;
        }
        
        switch(loot.getSlot().getId()){
            case 2: //Chest
                _parent.getActiveCharacter().setItemByChestItemId(loot);
                break;
            case 3: //Legs
                _parent.getActiveCharacter().setItemByLegsItemId(loot);
                break;
            case 4: //Boots
                _parent.getActiveCharacter().setItemByBootsItemId(loot);
                break;
            case 5: //Weapon
                _parent.getActiveCharacter().setItemByWeaponItemId(loot);
                break;
        }
        UpdateCharacterLoot();
    }//GEN-LAST:event_btn_EquipActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        Reset();
        UpdateCharacterLoot();
    }//GEN-LAST:event_formAncestorAdded

    public void Reset(){
        loot = null;
        
        lbl_ItemName.setText("");
        lbl_ItemSlot.setText("");
        lbl_ItemAtt1.setText("");
        lbl_ItemAtt2.setText("");
        
        _parent.ChangeIcon(lbl_ChestIcon, "Slot-Chest");
        _parent.ChangeIcon(lbl_FeetIcon, "Slot-Feet");
        _parent.ChangeIcon(lbl_LegsIcon, "Slot-Legs");
        _parent.ChangeIcon(lbl_WeaponIcon, "Slot-Weapon");
        _parent.ChangeIcon(lbl_LootIcon, "Slot-Loot");
        
        _parent.ChangeIcon(lbl_IconRace, "Unknown");
        _parent.ChangeIcon(lbl_IconClass, "Unknown");
    }
    
    public void UpdateCharacterLoot(){
        lbl_CharacterName.setText(_parent.getActiveCharacter().getName());
        _parent.ChangeIcon(lbl_IconRace, _parent.getActiveCharacter().getRace().getIconPath());
        _parent.ChangeIcon(lbl_IconClass, _parent.getActiveCharacter().getCharclass().getIconPath());
        
        if (_parent.getActiveCharacter().getItemByChestItemId() != null) {
            _parent.ChangeIcon(lbl_ChestIcon, _parent.getActiveCharacter().getItemByChestItemId().getIconPath());
        }
        if (_parent.getActiveCharacter().getItemByBootsItemId() != null) {
            _parent.ChangeIcon(lbl_FeetIcon, _parent.getActiveCharacter().getItemByBootsItemId().getIconPath());
        }
        if (_parent.getActiveCharacter().getItemByLegsItemId() != null) {
            _parent.ChangeIcon(lbl_LegsIcon, _parent.getActiveCharacter().getItemByLegsItemId().getIconPath());
        }
        if (_parent.getActiveCharacter().getItemByWeaponItemId() != null) {
            _parent.ChangeIcon(lbl_WeaponIcon, _parent.getActiveCharacter().getItemByWeaponItemId().getIconPath());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChangeCharacter;
    private javax.swing.JButton btn_Equip;
    private javax.swing.JButton btn_Loot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_CharacterName;
    private javax.swing.JLabel lbl_ChestIcon;
    private javax.swing.JLabel lbl_FeetIcon;
    private javax.swing.JLabel lbl_IconClass;
    private javax.swing.JLabel lbl_IconRace;
    private javax.swing.JLabel lbl_ItemAtt1;
    private javax.swing.JLabel lbl_ItemAtt2;
    private javax.swing.JLabel lbl_ItemName;
    private javax.swing.JLabel lbl_ItemSlot;
    private javax.swing.JLabel lbl_LegsIcon;
    private javax.swing.JLabel lbl_LootIcon;
    private javax.swing.JLabel lbl_WeaponIcon;
    private javax.swing.JPanel pnl_Test;
    // End of variables declaration//GEN-END:variables
}
